export const FORMLY_INFO = {
  name: 'Formly',
  tagline: 'Create Beautiful, Conversational Forms in Minutes',
  description: 'Build engaging forms with a modern, user-friendly interface. Collect responses, analyze data, and integrate with your favorite tools.',
  features: [
    {
      id: 1,
      title: 'Drag & Drop Builder',
      description: 'Create forms easily with our intuitive drag-and-drop interface',
      icon: 'drag_indicator',
      category: 'Builder',
    },
    {
      id: 2,
      title: 'Smart Logic',
      description: 'Add conditional logic to create dynamic, conversational forms',
      icon: 'psychology',
      category: 'Builder',
    },
    {
      id: 3,
      title: 'Real-time Analytics',
      description: 'Track responses and analyze data with powerful insights',
      icon: 'analytics',
      category: 'Analytics',
    },
    {
      id: 4,
      title: 'Team Collaboration',
      description: 'Work together with your team to create and manage forms',
      icon: 'group',
      category: 'Team',
    },
    {
      id: 5,
      title: 'Integrations',
      description: 'Connect with your favorite tools and automate workflows',
      icon: 'integration_instructions',
      category: 'Integrations',
    },
    {
      id: 6,
      title: 'Templates',
      description: 'Start quickly with professionally designed form templates',
      icon: 'dashboard',
      category: 'Templates',
    },
  ],
  integrations: [
    {
      id: 'google-sheets',
      name: 'Google Sheets',
      description: 'Export responses automatically to Google Sheets',
      category: 'Spreadsheets',
      icon: 'table_chart',
    },
    {
      id: 'slack',
      name: 'Slack',
      description: 'Get notified of new responses in Slack',
      category: 'Communication',
      icon: 'chat',
    },
    {
      id: 'zapier',
      name: 'Zapier',
      description: 'Connect with 3000+ apps through Zapier',
      category: 'Automation',
      icon: 'bolt',
    },
    {
      id: 'mailchimp',
      name: 'Mailchimp',
      description: 'Add respondents to your Mailchimp lists',
      category: 'Email Marketing',
      icon: 'mail',
    },
    {
      id: 'hubspot',
      name: 'HubSpot',
      description: 'Create contacts and deals in HubSpot',
      category: 'CRM',
      icon: 'people',
    },
    {
      id: 'stripe',
      name: 'Stripe',
      description: 'Accept payments through your forms',
      category: 'Payments',
      icon: 'payments',
    },
  ],
  pricing: {
    free: {
      name: 'Free',
      price: 0,
      features: [
        'Up to 100 responses/month',
        'Basic form fields',
        'Email notifications',
        'Export to CSV',
      ],
    },
    pro: {
      name: 'Pro',
      price: 29,
      features: [
        'Unlimited responses',
        'Advanced form fields',
        'Custom branding',
        'File uploads',
        'Priority support',
      ],
    },
    enterprise: {
      name: 'Enterprise',
      price: 99,
      features: [
        'Everything in Pro',
        'Custom domain',
        'SSO authentication',
        'Advanced security',
        'Dedicated support',
      ],
    },
  },
  industries: [
    'Technology',
    'Marketing & Advertising',
    'Education',
    'Healthcare',
    'Financial Services',
    'E-commerce',
    'Real Estate',
    'Non-profit',
    'Other',
  ],
  roles: [
    'Business Owner',
    'Marketing Manager',
    'Sales Representative',
    'HR Manager',
    'Product Manager',
    'Customer Support',
    'Developer',
    'Other',
  ],
}; 